### ISSUE TITLE
SDL3_net returns negative values on failure

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL_net#111]
A few SDL3_net functions return negative values on failure.
These should probably be changed into returning false on failure.

**Comment by icculus** [comment]
This turned out to be only a few of the functions.

Most of the things returning int are doing -1==failure, 1==success, 0==wouldblock. 

These sort of three-state return codes moved to enums in SDL3 (SDL_AppResult, SDL_EnumResult, etc), and we should maybe do that here, too.

**Comment by madebr** [comment]
Indeed, let's create an issue for that so we don't forget about it.

**Comment by icculus** [comment]
Done!
