### ISSUE TITLE
SDL2_net missing VS2010 and VS2012 solutions

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_net#23]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Windows 7, x86

# Comments on the original bug report:

On 2013-06-27 13:16:25 +0000, Mark Trettin wrote:

> The latest source tree is missing Visual Studio 2010 and 2012 solutions

**Comment by sezero** [comment]
Looks like VS2010 project files have been in there for some time.
