### ISSUE TITLE
configure.in should be renamed to configure.ac, AC_INIT() and AM_INIT_AUTOMAKE() calls

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_net#25]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2013-10-29 16:37:15 +0000,  wrote:

> Hi,
> 
> NOTE: This applies to all SDL modules and main libraries, only reporting to SDL_net at the moment.
> 
> With these versions of the tools:
> automake 1.14
> autoconf 2.69
> 
> I can see the following warnings (separated with empty lines to try to make them more clear), which will make compilations fail with autoconf 2.70 and automake 2.0 in the future [1].  So no hurry, but it will be good to migrate in the next releases.
> 
> Hope that helps.
> 
> 
> -----------------------------------
> aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
> 
> libtoolize: putting auxiliary files in `.'.
> libtoolize: copying file `./ltmain.sh'
> libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.in and
> libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
> libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
> 
> aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
> 
> automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
> 
> configure.in:45: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
> configure.in:45: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
> configure.in:29: installing './compile'
> 
> automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
> -----------------------------------
> 
> 
> [1] http://lists.gnu.org/archive/html/automake/2013-06/msg00040.html
> 
>   The 1.14 release also introduces new (non-fatal) runtime warnings to
>   simplify the transition to Automake 2.0.  You are free to ignore such
>   warnings for now, but should address them before the transition to
>   Automake 2.0 (whose ETA is about one year from now, maybe more, so no
>   need to hurry yet).
>   [...]
> 
>   * WARNING: Future backward-incompatibilities!
>   [...]
> 
>   - Automake 2.0 will require Autoconf 2.70 or later (which is still
>     unreleased at the moment of writing, but is planned to be released
>     before Automake 2.0 is).
> 
>   - Automake 2.0 will drop support for the long-deprecated 'configure.in'
>     name for the Autoconf input file.  You are advised to start using the
>     recommended name 'configure.ac' instead, ASAP.

**Comment by sezero** [comment]
These issues have been fixed in git
