### ISSUE TITLE
[PATCH] little MemLeak

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_net#27]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch for memleak (memleak.patch, text/plain, 2015-01-24 23:30:42 +0000, 653 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2004)

**Reported in version:** 2.0.0
**Reported for operating system, platform:** Windows (All), x86_64

# Comments on the original bug report:

On 2015-01-24 23:30:42 +0000, Jean-Baptiste Noblot wrote:

> Created attachment 2004
> Patch for memleak
> 
> We reassign directly the same var with realloc but if realloc fail we loose the pointer
> 
> SDLnet.c line 239
> 
> so the patch make a tmpVar and assign after

**Comment by icculus** [comment]
I updated this patch for the `SDL2` branch in 4f31a95cd8fd380e9e9b91ce016fe2ff288739f5, `release-2.2.x` in 666d9c9e44d8108cdb677ebe917aa7c8aab389e7, and `SDL-1.2` in 83ba32df29225b0f29be1a6d66e678b1b1cb01ac.

It wasn't necessary for SDL3_net.
