### ISSUE TITLE
Enable IPV6 feature in SDL_net 1.2.8.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_net#28]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [IPV6 Patch (PatchIPV6, text/plain, 2015-04-24 08:59:22 +0000, 23256 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2132)
* [updated patch for sdl2_net-2.0.1 (patch, text/plain, 2016-08-03 00:20:39 +0000, 22612 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=2536)

**Reported in version:** 1.2.8
**Reported for operating system, platform:** Linux, x86

# Comments on the original bug report:

On 2015-04-24 08:59:22 +0000, Nitz wrote:

> Created attachment 2132
> IPV6 Patch
> 
> Hi,
> I have implemented IPV6 support in SDL_net-1.2.8 version, 
> 
> which means if Server is dual stack then Server can communicate with IPV6 and IPV4 clients both at same time.
> 
>  
> 
> I have done best possible changes with optimization in SDL_net as all of the API signatures are same except  SDLNet_UDP_Open
> 
>  
> 
> Kindly review and release the changes as per your policy.
> 
>  
> 
> If having any doubts please ask.
> 
> 
> Attaching the Patch with IPV6 changes
> 
> 
> Build steps:
> 
> export CPPFLAGS=-DDUAL_IP
> 
> ./configure
> 
> make all
> 
> make install

On 2015-05-20 13:08:07 +0000, Nitz wrote:

> (In reply to Nitz from comment # 0)
> > Created attachment 2132 [details]
> > IPV6 Patch
> > 
> > Hi,
> > I have implemented IPV6 support in SDL_net-1.2.8 version, 
> > 
> > which means if Server is dual stack then Server can communicate with IPV6
> > and IPV4 clients both at same time.
> > 
> >  
> > 
> > I have done best possible changes with optimization in SDL_net as all of the
> > API signatures are same except  SDLNet_UDP_Open
> > 
> >  
> > 
> > Kindly review and release the changes as per your policy.
> > 
> >  
> > 
> > If having any doubts please ask.
> > 
> > 
> > Attaching the Patch with IPV6 changes
> > 
> > 
> > Build steps:
> > 
> > export CPPFLAGS=-DDUAL_IP
> > 
> > ./configure
> > 
> > make all
> > 
> > make install

On 2015-05-20 13:10:35 +0000, Nitz wrote:

> Hi Mr.Sam,
> Any updates regarding IPV6 enhancement in SDL_net?
> Please feel free if having any doubts.
> 
> Regards,
> Nitin

On 2015-07-22 09:06:08 +0000, Nitz wrote:

> A gentle reminder!!!
> 
> Thanks...

On 2015-07-22 19:23:20 +0000, Philipp Wiesemann wrote:

> Bug 283 also has patches for IPv6.

On 2015-07-23 03:50:42 +0000, Nitz wrote:

> Yes. I have seen that but the patch which I suggested has minimal changes as compared to Bug 283 and important thing is API signatures are also same except  SDLNet_UDP_Open.
> You can compare and take the decision as currently I am using the same patch successfully.

On 2015-09-29 05:54:08 +0000, Nitz wrote:

> A gentle reminder!!!
> Thanks.

On 2016-08-03 00:20:39 +0000,  wrote:

> Created attachment 2536
> updated patch for sdl2_net-2.0.1
> 
> I merged Nitz's patch with sdl2_net-2.0.1 and removed the #defines so the code isn't dependent on DUAL_IP being defined. It's not a very nice diff to look at, but perhaps it will save someone else some work.
> 
> I don't know much about IPv6 but I did test this against both IPv4 and IPv6 networks, and it seems to work fine.

On 2018-05-25 21:53:53 +0000, Eric wing wrote:

> Just wondering what the status of IPv6 in SDL_net is. Apple's App Stores require IPv6 operability as of 2 years ago. They seem to have an automated way to test compliance so they can automatically reject IPv4 only apps. 
> 
> So it would be really useful to have IPv6 support now.

**Comment by SopaDeMacaco-UmaDelicia** [comment]
AYoooo, bump

**Comment by icculus** [comment]
There is also a patch in #5, let's evaluate these both and see if either make sense.

**Comment by icculus** [comment]
We're dumping this patch and figuring this out from-scratch in #40.

**Comment by icculus** [comment]
SDL3_net supports IPv6, so I'm calling this done.
