### ISSUE TITLE
SDL_net UWP validation fail

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_net#30]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Other, x86

# Comments on the original bug report:

On 2017-06-11 06:14:19 +0000, Ryan C. Gordon wrote:

> Apparently SDL_net uses two win32 APIs that are forbidden on the Windows Store. Discussion is here:
> 
> https://discourse.libsdl.org/t/sdl-net-uwp-validation-fail/22609
> 
> One can (probably) be #ifdef'd out for UWP builds if nothing else, the other can probably be replaced with SIO_GET_INTERFACE_LIST.
> 
> --ryan.

**Comment by madebr** [comment]
SDL3 dropped UWP support, so I think it's safe to close this issue.

**Comment by icculus** [comment]
This is arguably a problem for SDL2 apps still, but I'm fine with this staying closed.
