### ISSUE TITLE
Support to IPV6

### ISSUE THREAD

**Issue by daywithstars** [libsdl-org/SDL_net#40]
Any plan to support ip version 6 in the future ?

**Comment by SopaDeMacaco-UmaDelicia** [comment]
AYoooo, bump

**Comment by icculus** [comment]
#5 and #28 both have patches, so let's close this one as a duplicate and figure out what to do in one of those.

**Comment by icculus** [comment]
Actually, both those patches break ABI.  :/

**Comment by slouken** [comment]
Breaking ABI is fine in SDL_net 3.0 ;)

**Comment by icculus** [comment]
SDL3_net supports IPv6, so I'm calling this done.
