### ISSUE TITLE
remove support for 'chat' program?

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL_net#41]
@slouken, @icculus: the GUIlib library hasn't been maintained for 14 years
and doesn't support SDL2. Remove support for it (the 'chat' program) at least
from SDL2? (maybe also from SDL-1.2, but it still builds I guess..)

**Comment by icculus** [comment]
I'm going to assign this to me, to see if there's a reasonable option to keep it, but I likely won't get to this for a little while; if someone wants to take it in the meantime, just say so.

**Comment by henke37** [comment]
At the very least example programs don't belong in the same directory as the main library code.

**Comment by sezero** [comment]
> I'm going to assign this to me, to see if there's a reasonable option to keep it

It may be a nice example program, but not buildable with SDL2_net.

**Comment by sezero** [comment]
This can be closed after recent changes and updated GUIlib here at github.
