### ISSUE TITLE
Please update `configure`

### ISSUE THREAD

**Issue by giordano** [libsdl-org/SDL_net#43]
It'd be great to update `configure`, it's 10-year old: https://github.com/libsdl-org/SDL_net/blob/03e0cc6b437d55b49b66967b745a04c74b7ee67d/configure#L6  I can't build shared libraries for powerpc64le and freebsd because of this reason, regenerating it with a newer version of autoconf would be great :slightly_smiling_face:

**Comment by giordano** [comment]
As I said, I can't build shared libraries.  For example https://github.com/libsdl-org/SDL_net/blob/03e0cc6b437d55b49b66967b745a04c74b7ee67d/configure#L8256-L8257 and https://github.com/libsdl-org/SDL_net/blob/03e0cc6b437d55b49b66967b745a04c74b7ee67d/configure#L9154-L9155 hardcode that for FreebBSD 1* shared libraries aren't supported, which is just false.  This is a recurring problem with _old_ configure scripts.  Just regenerating with a version more recent of autoconf would do it.

**Comment by giordano** [comment]
This is for example what I just had to do to build SDL2_net with [BinaryBuilder](https://binarybuilder.org/) for these platforms: [JuliaPackaging/Yggdrasil@`2369be1` (#4609)](https://github.com/JuliaPackaging/Yggdrasil/pull/4609/commits/2369be10910feddc697b3635bd2537f74279099a).  As I said, this is such a frequent issue that it has a dedicated entry in the troubleshooting section of the manual: https://docs.binarybuilder.org/stable/troubleshooting/#Shared-library-not-built

**Comment by sezero** [comment]
Seems to be an issue with libtool, not autoconf. Will try looking into.

**Comment by sezero** [comment]
Importing the following two mainstream libtool commits should fix this:
http://git.savannah.gnu.org/gitweb/?p=libtool.git;a=commitdiff;h=e94c6d6e0359d92f08f491f57e0ef3371e978952
http://git.savannah.gnu.org/gitweb/?p=libtool.git;a=commitdiff;h=49ae2888b43cad358e2ff60a69722341116e7b40

Preparing patches for all SDL projects.

**Comment by sezero** [comment]
As to why I don't upgrade to newest libtool (which I actually had done,
but gone back to 2.2.6: https://github.com/libsdl-org/SDL/issues/5040),
is because of this ridiculous libtool bug:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=52253

**Comment by sezero** [comment]
Fixed in git.  If any more issues are present, please drop a note here.
