### ISSUE TITLE
Cannot extract SDL2_net-2.2.0.tar.gz with msys2

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL_net#59]
Extracting the latest SDL2_net 2.2.0 release on Windows, using msys2, gives the following error:

```
$ tar xf SDL2_net-2.2.0.tar.gz
tar: SDL2_net-2.2.0/Xcode/macOS/SDL2.framework/Resources: Cannot create symlink to ‘Versions/Current/Resources’: No such file or directory
tar: SDL2_net-2.2.0/Xcode/macOS/SDL2.framework/Headers: Cannot create symlink to ‘Versions/Current/Headers’: No such file or directory
tar: SDL2_net-2.2.0/Xcode/macOS/SDL2.framework/SDL2: Cannot create symlink to ‘Versions/Current/SDL2’: No such file or directory
tar: Exiting with failure status due to previous errors
```

**Comment by Biswa96** [comment]
SDL2_net had been updated to 2.2.0 in msys2. See this commit https://github.com/msys2/MINGW-packages/commit/323b2cf73c2a5389e73a164912fc4a1ba93567f7. ZIP file is used instead of .tar.gz to resolve the symlink issue. It's common in many msys2 mingw packages.

**Comment by slouken** [comment]
Packaging up the Xcode directory would add an additional step for people building on Apple platforms, and given that Windows folks are expected to use the zip files in any case, I think we'll leave this as-is for now.
