### ISSUE TITLE
Cmake: The generated pc file is broken

### ISSUE THREAD

**Issue by autoantwort** [libsdl-org/SDL_net#72]
The pc.in file uses variables that are not defined in cmake. This results in a duplicated `Libs:` entry. 

Maybe simply drop support for pkgconfig files for cmake.

**Comment by autoantwort** [comment]
> I suppose you mean `INETLIB` not being set?

Yeah and `ENABLE_SHARED_TRUE`, `ENABLE_STATIC_TRUE` and `ENABLE_SHARED_FALSE`.

**Comment by madebr** [comment]
Those variables are set, but the current cmake script builds either a shared or a static library. Never both.

I will probably change this for SDL3 in all SDL satellite libraries, and allow building both.

**Comment by autoantwort** [comment]
And where are they set? I have not found it

**Comment by madebr** [comment]
Yes and no, I decreased their indentation.
They were already being set.
